# Generated by Django 4.2.2 on 2023-06-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0002_alter_register_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
