# Generated by Django 4.2.2 on 2023-06-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0003_remove_register_confirm_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='first_name',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='last_name',
            new_name='Lname',
        ),
    ]
