# Generated by Django 4.2.2 on 2023-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0004_rename_first_name_register_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(blank=True, default='INDIA', max_length=50, null=True),
        ),
    ]
