# Generated by Django 4.2.2 on 2023-06-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0005_alter_register_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('standard', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default='VII', max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('postalpcode', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('INDIA', 'INDIA'), ('OTHERS', 'OTHERS')], default='INDIA', max_length=50)),
                ('DOB', models.DateTimeField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'others')], default='others', max_length=30)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
