# Generated by Django 4.2.2 on 2023-06-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0007_alter_student_records_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_records',
            name='country',
            field=models.CharField(choices=[('INDIA', 'INDIA'), ('OTHERS', 'OTHERS')], default='INDIA', max_length=50),
        ),
    ]
