# Generated by Django 4.2.2 on 2023-06-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0008_alter_student_records_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_records',
            name='standard',
            field=models.CharField(choices=[('None', 'None'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default='VII', max_length=20),
        ),
    ]
