# Generated by Django 4.2.2 on 2023-06-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0010_roommember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomMember',
        ),
    ]
